---
title: "Getting taxonomy / tree"
author: "Dan Benesh"
date: "February 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(stringsAsFactors = FALSE)
theme_set(new = theme_bw())
```

I need several datasets to address these issues: (i) host associations for the parasites in the life cycle database,
(ii) life history variables for species in the life cycle database (body sizes and development), (iii) host body masses, and (iv) host taxonomy.

```{r importdata}
hosts <- read.csv(file = "../data/CLC_database_hosts.csv", header = TRUE) 
lh <- read.csv(file = "../data/CLC_database_lifehistory.csv", header = TRUE)
host_mass <- read.csv(file = "../data/collated_host_mass_data.csv", header = TRUE)
host_tax <- read.csv(file = "../data/ncbi_host_taxonomy.csv", header = TRUE)
```

```{r}
nem_genus <- filter(hosts, Parasite.group == 'nematode')%>%select(Parasite.genus)%>%distinct()
nem_genus <- nem_genus$Parasite.genus
ces_genus <- filter(hosts, Parasite.group == 'cestode')%>%select(Parasite.genus)%>%distinct()
ces_genus <- ces_genus$Parasite.genus
aca_genus <- filter(hosts, Parasite.group == 'acanthocephalan')%>%select(Parasite.genus)%>%distinct()
aca_genus <- aca_genus$Parasite.genus
```

GET API KEY!

```{r}
library(taxize)

# get taxonomic classification from ncbi; WARNING takes a while!
genera_class <- classification(p_genus[1:10], db = 'ncbi', rows = 1, verbose = FALSE, )
```

```{r}
# re-arrange data returned from ncbi database
worm.taxonomy <- rbind(genera_class)%>%
  select(name, rank, query)%>% # reduce list to df and select relevant columns
  filter(rank != "no rank")%>% # remove unnecessary categories
  spread(rank, name)%>% # long to wide data
  select(query, genus, family, order, class, phylum, kingdom)

# remove some obviously incorrect values
worm.taxonomy <- filter(worm.taxonomy, kingdom == "Metazoa")
worm.taxonomy <- filter(worm.taxonomy, phylum == "Acanthocephala" | phylum == "Nematoda" | phylum == "Platyhelminthes")
```

# SAVE IT NOW


```{r}
library(rotl)
```

```{r}
tnrs_contexts()
```


```{r}
aca_search <- tnrs_match_names(names = aca_genus[1:10], context_name = "Animals")
ces_search <- tnrs_match_names(names = ces_genus[1:10], context_name = "Platyhelminthes")
nem_search <- tnrs_match_names(names = nem_genus[1:10], context_name = "Nematodes")
```

```{r}
taxonomy_taxon_info(ott_id(taxon_search))
ott_in_tree <- ott_id(taxon_search)[is_in_tree(ott_id(taxon_search))]
tr <- tol_induced_subtree(ott_ids = ott_in_tree, label_format = 'name')
```
```{r}
plot(tr)
```

```{r}
tr
```

```{r}
taxon_search
inspect(taxon_search, taxon_name = 'capillaria')
```

