---
title: "Getting taxonomic tree to map invasion of ungulates"
author: "Dan Benesh"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(taxize)
library(rotl)
library(ape)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(stringsAsFactors = FALSE)
theme_set(new = theme_bw())
```

```{r}
# list of helminth fams in ungulates - from MS
monogenes <- "Polystomatidae"
cestodes <- c('Diphyllobothridae', 'Anoplocephalinae', 'Linstowiinae', 'Thysanosomatinae', 'Inermicapsiferinae',
              'Davaineidae', 'Taeniidae')
trematodes <- c('Hasstilesiidae', 'Schistosomatidae', 'Echinostomatidae', 'Fasciolidae', 'Paramphistomidae',
              'Balanorchiidae', 'Brumptiidae', 'Choerocotyloididae', 'Cladorchiidae', 'Gastrodiscidae',
              'Gastrothylacidae', 'Olveriidae', 'Stephanopharyngidae', 'Zygocotylidae', 'Notocotylidae',
              'Opisthorchiidae', 'Heterophyidae', 'Dicrocoeliidae', 'Paragonimidae')
nematodes <- c('Capillariidae', 'Robertdollfusidae', 'Trichinellidae', 'Trichuridae', 'Ancylostomatidae',
               'Ascarididae', 'Chabertiidae', 'Cooperiidae', 'Dictyocaulidae', 'Filariidae', 'Gnathostomatidae',
               'Gongylonematidae', 'Habronematidae', 'Haemonchidae', 'Metastrongylidae', 'Molineidae',
               'Onchocercidae', 'Oxyuridae', 'Protostrongylidae', 'Spirocercidae', 'Strongylidae', 'Strongyloididae',
               'Syngamidae', 'Thelaziidae', 'Trichostrongylidae')
acanths <- c('Oligacanthorhynchidae','Echinorhynchidae')
```

```{r}
# check to see if they are all in tree
mono_search <- tnrs_match_names(names = monogenes, context_name = "Platyhelminthes")
cest_search <- tnrs_match_names(names = cestodes, context_name = "Platyhelminthes")
trem_search <- tnrs_match_names(names = trematodes, context_name = "Platyhelminthes")
nema_search <- tnrs_match_names(names = nematodes, context_name = "Nematodes")
acan_search <- tnrs_match_names(names = acanths, context_name = "Animals")
# only cest fams have problem - subfamilies of Anoplocephalidae not all recognized
```


```{r}
# make a tree with helminth families in ungulates

# combine taxa and check whether they are in treee
ott <- c(ott_id(mono_search), ott_id(cest_search), ott_id(trem_search), ott_id(nema_search), ott_id(acan_search))
ott_in_tree <- ott[is_in_tree(ott)]
# attributes erased by appending lists together - re-add so subtree function works
attr(ott_in_tree, 'class') <- c("otl_ott_id", "list")
# get subtree
tree1 <- tol_induced_subtree(ott_ids = ott_in_tree, label_format = 'name')
```

```{r}
plot(tree1, show.node.label = T)
# looks ok
```


```{r}
# list of all helminth families - from OTL
```

```{r}
# make dataset - Family, Ung inf, Route
```


```{r}
# get tree of all helminth families
nem <- tnrs_match_names(names = "Nematoda", context_name = "Nematodes")
```
```{r}
taxonomy_taxon_info(ott_id(nem), include_lineage = T)
tax_lineage(taxonomy_taxon_info(ott_id(nem)))
```



```{r}
# list of helminth taxa in ungulates - from London NHM DB, need ungulates for cross-checking
```
